# Build
FROM node:22.22.3-alpine AS builder

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY tsconfig.base.json ./
COPY pnpm-lock.yaml ./

COPY packages/db/package.json ./packages/db/
COPY apps/dashboard/package.json ./apps/dashboard/

RUN pnpm install --frozen-lockfile

COPY packages/db ./packages/db
COPY apps/dashboard ./apps/dashboard

RUN pnpm --filter "@packages/db" build || true
RUN pnpm --filter "dashboard" build

# Run
FROM nginx:alpine AS runner

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/apps/dashboard/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 3000; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/dashboard.conf

EXPOSE 3000

CMD [ "nginx", "-g", "daemon off;" ]
