# Build
FROM node:22.22.3-alpine AS builder

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY tsconfig.base.json ./

COPY packages/db/package.json ./packages/db/
COPY packages/auth/package.json ./packages/auth/
COPY apps/dantes/package.json ./apps/dantes/

RUN pnpm install --frozen-lockfile

COPY packages/db ./packages/db
COPY packages/auth ./packages/auth
COPY apps/dantes ./apps/dantes

RUN pnpm --filter "@packages/db" build
RUN pnpm --filter "@packages/auth" build
RUN pnpm --filter "dantes" build


# Run
FROM node:22.22.3-alpine AS runner

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./

COPY --from=builder /app/packages/db/dist ./packages/db/dist
COPY --from=builder /app/packages/db/package.json ./packages/db/
COPY --from=builder /app/packages/auth/dist ./packages/auth/dist
COPY --from=builder /app/packages/auth/package.json ./packages/auth/
COPY --from=builder /app/apps/dantes/dist ./apps/dantes/dist
COPY --from=builder /app/apps/dantes/package.json ./apps/dantes/

RUN pnpm install --prod --frozen-lockfile

RUN mkdir -p /app/data

EXPOSE 6969

CMD [ "node", "apps/dantes/dist/index.js" ]
