events {
    worker_connections 1024
}

http {
    upstream dantes_server {
        server dantes-server:6969;
    }

    upstream dantes_dashboard {
        server dantes-dashboard:6969;
    }

    server {
        listen 80;

        location /api {
            proxy_pass http://dantes_server;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';

            rewrite ^/api(/.*)$ $1 break;
        }

        location /dashboard {
            proxy_pass http://dantes_dashboard;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 
            rewrite ^/dashboard(/.*)$ $1 break;
        }

        location = / {
            return 301 /dashboard;
        }

        location /health {
            access_log off;
            return 200 'dantes🧭 is alive!\n';
            add_header Content-Type text/plain;
        }
    }
}
