#!/bin/bash
set -e

bcrypt_hash() {
  local password="$1"
  local cost="${2:-12}"

  if [ -z "$password" ]; then
    echo "Error: No password provided" >&2
    return 1
  fi

  python3 -c "import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt(rounds=int(sys.argv[2]))).decode())" "$password" "$cost"
}


RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

echo ""
echo -e "${BOLD}${BLUE}╔═══════════════════════════════════════╗${NC}"
echo -e "${BOLD}${BLUE}║         dantes setup wizard           ║${NC}"
echo -e "${BOLD}${BLUE}╚═══════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}Checking dependencies...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}✗ Docker is not installed.${NC}"
    echo "  Please install Docker from https://docs.docker.com/get-docker/ and try again."
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}✗ Docker Compose is not available.${NC}"
    echo "  Please make sure you have Docker Desktop or docker-compose-plugin installed."
    exit 1
fi

echo -e "${GREEN}✓ Docker is ready${NC}"

echo -e "${YELLOW}Checking Python 3 and bcrypt...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${YELLOW}Python 3 not found. Installing...${NC}"
    if command -v brew &> /dev/null; then
        brew install python3
    elif command -v apt-get &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y python3
    elif command -v yum &> /dev/null; then
        sudo yum install -y python3
    else
        echo -e "${RED}✗ Cannot install Python 3 automatically.${NC}"
        echo "  Please install Python 3 manually and try again."
        exit 1
    fi
fi

echo -e "${GREEN}✓ Python 3 is ready${NC}"

if ! python3 -c "import bcrypt" 2>/dev/null; then
    echo -e "${YELLOW}bcrypt library not found. Installing...${NC}"
    python3 -m pip install bcrypt
    if [ $? -ne 0 ]; then
        echo -e "${RED}✗ Failed to install bcrypt.${NC}"
        echo "  Try running: pip3 install bcrypt"
        exit 1
    fi
fi

echo -e "${GREEN}✓ bcrypt is ready${NC}"
echo ""

if [ -f "./apps/dantes/.env" ] || [ -f "./packages/auth/.env" ] || [ -f "./packages/db/.env" ]; then
    echo -e "${YELLOW}⚠ .env files already exist.${NC}"
    read -p "  Overwrite them and reconfigure? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "  Keeping existing .env files. Starting dantes..."
        docker compose up -d
        echo ""
        echo -e "${GREEN}✓ dantes is running at http://localhost/dashboard${NC}"
        exit 0
    fi
    echo ""
fi

echo -e "${BOLD}Let's configure your dantes instance.${NC}"
echo ""

read -p "Dashboard username (email): " USERNAME
while [[ -z "$USERNAME" ]]; do
    echo -e "${RED}  Username cannot be empty.${NC}"
    read -p "Dashboard username (email): " USERNAME
done

while true; do
    read -s -p "Dashboard password: " PASSWORD
    echo ""
    read -s -p "Confirm password: " PASSWORD_CONFIRM
    echo ""
    if [[ "$PASSWORD" == "$PASSWORD_CONFIRM" ]]; then
        break
    fi
    echo -e "${RED}  Passwords do not match. Try again.${NC}"
done

while [[ -z "$PASSWORD" ]]; do
    echo -e "${RED}  Password cannot be empty.${NC}"
    read -s -p "Dashboard password: " PASSWORD
    echo ""
done

echo ""
echo -e "${YELLOW}Base callback URL is the publicly accessible URL of your worker app.${NC}"
echo -e "${YELLOW}Leave blank if you'll configure this later.${NC}"
read -p "Base callback URL (optional, e.g. https://myapp.com): " BASE_CALLBACK_URL
echo ""

if command -v openssl &> /dev/null; then
    JWT_SECRET=$(openssl rand -base64 48)
elif command -v python3 &> /dev/null; then
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
else
    JWT_SECRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)
fi

echo -e "${GREEN}✓ JWT secret generated automatically${NC}"

echo -e "${YELLOW}Hashing password with bcrypt...${NC}"
HASHED_PASSWORD=$(bcrypt_hash "$PASSWORD" "12")
if [ $? -ne 0 ]; then
    echo -e "${RED}✗ Failed to hash password. Using plain password (not recommended).${NC}"
    HASHED_PASSWORD="$PASSWORD"
fi
echo -e "${GREEN}✓ Password hashed successfully${NC}"

cat > ./apps/dantes/.env << EOF
# Generated by dantes setup script on $(date)
# Do not share this file — it contains secrets

# ── Server ────────────────────────────────────────────────────────────────────
DANTES_PORT="6969"
FRONTEND_URL="http://localhost/dashboard"
BASE_CALLBACK_URL="${BASE_CALLBACK_URL}"

# ── Scheduler ─────────────────────────────────────────────────────────────────
WAIT_TIME_MS="1000"
DEFAULT_WAIT_TIME_MS="500"
MAX_JOB_CONCURRENCY="5"
DEFAULT_REPLY_WAIT_TIME="600000"

# ── Database ──────────────────────────────────────────────────────────────────
DB_FILE_PATH="/app/data/dantes.db"

# ── Auth ──────────────────────────────────────────────────────────────────────
JWT_SECRET="${JWT_SECRET}"
HASH_ROUNDS="12"

# ── Dashboard Login ───────────────────────────────────────────────────────────
USERNAME="${USERNAME}"
PASSWORD="${HASHED_PASSWORD}"
EOF

cat > ./packages/auth/.env << EOF
# Generated by dantes setup script on $(date)
# Do not share this file — it contains secrets

JWT_SECRET="${JWT_SECRET}"
HASH_ROUNDS="12"

USERNAME="${USERNAME}"
PASSWORD="${HASHED_PASSWORD}"
EOF

cat > ./packages/db/.env << EOF
# Generated by dantes setup script on $(date)
# Do not share this file — it contains secrets

DB_FILE_PATH="../../dantes.db"
EOF

echo -e "${GREEN}✓ .env files written:${NC}"
echo "  - ./apps/dantes/.env"
echo "  - ./packages/auth/.env"
echo "  - ./packages/db/.env"
echo ""

echo -e "${YELLOW}Building and starting dantes (this may take a few minutes on first run)...${NC}"
echo ""

docker compose up -d --build

echo ""
echo -e "${BOLD}${GREEN}╔═══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║   ✓ dantes is up and running!             ║${NC}"
echo -e "${BOLD}${GREEN}╚═══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Dashboard: ${BLUE}http://localhost/dashboard${NC}"
echo -e "  API:       ${BLUE}http://localhost/api${NC}"
echo ""
echo -e "  Login with the credentials you just set up."
echo ""
echo -e "${YELLOW}Useful commands:${NC}"
echo -e "  Stop dantes:    ${BOLD}docker compose down${NC}"
echo -e "  View logs:      ${BOLD}docker compose logs -f${NC}"
echo -e "  Restart:        ${BOLD}docker compose restart${NC}"
echo ""